### ISSUE TITLE
Docker Support

### ISSUE THREAD

**Issue by DragonRex004** [VountyNetwork/Wizard#1]
Hey VountyNetwork, 
ein cooles Projekt was ihr da mit Wizard gestartet habt. Nur mir fehlt leider noch der Docker Support.
Deshalb wäre es cool, wenn ihr noch Docker Support für Wizard machen würdet.
(Als Docker Image)

**Comment by ShortyPing** [comment]
Die Software unterstützt jetzt Docker-Compose, wir werden uns bemühen, die Software auch als Docker-Image auf docker.io zur Vefügung zu stellen.
