### ISSUE TITLE
Cannot deploy smaller repositories

### ISSUE THREAD

**Issue by NonSwag** [VountyNetwork/Wizard#13]
https://github.com/VountyNetwork/Wizard/blob/06ef8b7956cb2e887554e75378ea19ed4c35385d/src/main/java/net/vounty/wizard/repository/WizardRepository.java#L91
When deploying small repositories (<  25 files) to Wizard, the deployment is ignored and doesn't work.

**Comment by StonksCloud** [comment]
Has there already been a case where less than 25 files were deployed? 
My tests have shown that 25 files are always deployed.

**Comment by NonSwag** [comment]
Yes two cases.
Bot had either no documentations or sources included and the file count was
12.

**Comment by GradientTim** [comment]
Should be fixed now in [1.0.6](https://github.com/VountyNetwork/Wizard/releases/tag/1.0.6)
