### ISSUE TITLE
403 error code, even when succeeded

### ISSUE THREAD

**Issue by NonSwag** [VountyNetwork/Wizard#14]
I've updated to [1.0.6](https://github.com/VountyNetwork/Wizard/releases/tag/1.0.6) and receive the 403 response when I deploy an artifact.
#### Steps to reproduce:
> Deploy a repository which does not already exist
#### Expected behavior:
> Should respond with code 200 and upload the repository
#### What happens instead:
> The server responds with code 403, but uploads the repository

**Comment by NonSwag** [comment]
Sorry I've mixed something up.
Small correction: This issue does not occur if the repository does not exist.
It occurs only when it already exists with a different version.

**Comment by GradientTim** [comment]
Is an exception sent or do you just get the error code?

I have read out the following from your issue, tried it and had no errors.
- Created new repository (or used existing)
- Deployed 2x or more with different versions

**Comment by NonSwag** [comment]
I don't receive any exception but just the error code

**Comment by GradientTim** [comment]
Can you test if [this](https://cdn.vounty.net/wizard/Wizard-1.0.7-TEST.jar) works for you?

**Comment by NonSwag** [comment]
Will try it tomorrow, just finished up for today.
