### ISSUE TITLE
Special character passwords not working

### ISSUE THREAD

**Issue by NonSwag** [VountyNetwork/Wizard#3]
A password like this `r3-mx!3n4T03lcNMF§-eErFk§F*Qb?=?` does not work and produces an 401 unauthorized error when deploying my artifact
But passwords like this `UsIUsxnwuffwTVfCeME4xBBte6l7mMcE` do
The website is not affected by this problem, only m2.

**Comment by StonksCloud** [comment]
Hey NonSwag,
did you try to use CDATA in the Maven settings file?
It looks like this in the password field: `<![CDATA[**DEPLOY_PASSWORD**]]>`
Just replace the `**DEPLOY_PASSWORD**` with your original password.

Found this solution at [MuleSoft](https://help.mulesoft.com/s/article/Maven-deployment-fails-with-401-Unauthorized-error-when-the-password-contains-special-characters)

**Comment by NonSwag** [comment]
Sorry but it doesn't work either
I think it is an unescaping issue on wizard's side
could you take a look at it?
Thanks in advance

**Comment by StonksCloud** [comment]
After a little debugging, i found the issue an hopefully fixed it in [1.0.3](https://github.com/VountyNetwork/Wizard/releases/tag/1.0.3)

Let me know if it works as well on your system now as it does for me.

**Comment by NonSwag** [comment]
Thank you for the quick fix.
I'll try it tonight and let you know how it goes.

**Comment by NonSwag** [comment]
Yesterday it didn't work, so I reinstalled everything and went through the setup all over, but still no changes
The password I was using was: `JEWNVo{°FHtZwkp(;Qm\'Dj..YSHlµ4|`

I am using the .m2 file to store my password. Maybe it is a fault on my end, so if you have any suggestions, feel free to tell.
https://hastebin.com/izolulaqoy.xml

**Comment by NonSwag** [comment]
Are there any news about this topic?

**Comment by StonksCloud** [comment]
Yes, I found out that there are problems with encoding an arbitrary string.
I tried some other Java libraries that support the BCrypt algorithm, but none of them were able to hash the string with the characters.

There are optional solutions for you:
- Use a password that does not contain special characters.
- Regenerate the password every week (or at another interval)

You can regenerate a password with the command:
`token modify TOKEN_NAME password --generate`

**Comment by NonSwag** [comment]
I've done some tests and I found out that the password is (probably) not encoded using ISO_8859_1
the content of the header: `dGVzdDo/P10/Pz8uPz9dWz8/P1t9XT8=`
the decoded header: `test:??]???.??][???[}]?`
the bytes are not encoded using utf-8 or any other standard charset.
Maybe you can find out which charset maven uses to encode the header.
