### ISSUE TITLE
Default colorscheme for all users

### ISSUE THREAD

**Issue by NonSwag** [VountyNetwork/Wizard#9]
### Discussed in https://github.com/VountyNetwork/Wizard/discussions/6

<div type='discussions-op-text'>

<sup>Originally posted by **NonSwag** January 11, 2023</sup>
An option which defines the default style of the website (either dark or light mode)
This option will define the style of the website when no application data was found for the `theme` key
I am terrible at explaining, so feel free to ask if something is unclear.</div>

**Comment by StonksCloud** [comment]
Replied [here](https://github.com/VountyNetwork/Wizard/discussions/6#discussioncomment-4682034)
